### PR TITLE
pr4

### PR DESCRIPTION
**Pull request by LucasDvp**

### CODE REVIEW

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-35) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140747419843-35%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mOw7CSi3HQpbDQCXHA0LU1aOUBrtP9eBU6W9XZKWr6E%3D&st=2018-09-14T07%3A43%3A27Z&se=2018-10-15T07%3A48%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-35) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140747422983-35%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=10lD7McFfgBeAEBREKCtcEOC3UMm0reGTsAezGwuFWg%3D&st=2018-09-14T07%3A43%3A32Z&se=2018-10-15T07%3A48%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-35) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140748482569-35%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wqBsX6xFZeYXR%2F5HS7Mn7bhRZ7YP%2FK6olfGbfHftpQw%3D&st=2018-09-14T07%3A44%3A48Z&se=2018-10-15T07%3A49%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-35) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140748557610-35%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=n8L7hkAGuLzOqw%2Br%2BPANtiwZahQs6ILegsLsTpZWtLE%3D&st=2018-09-14T07%3A44%3A57Z&se=2018-10-15T07%3A49%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-35) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140753241313-35%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qInjbyiAs6%2BQcoC9DaVEDwaF559yLT2LGPEbfN4DBkM%3D&st=2018-09-14T07%3A49%3A14Z&se=2018-10-15T07%3A54%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-35) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140753481200-35%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=de3G5jcEh1bX6wCNyzr92hCdVKI0jtnbMfVddkRPqZM%3D&st=2018-09-14T07%3A49%3A46Z&se=2018-10-15T07%3A54%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-35) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140755036999-35%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xIYg3nl%2FUViEsKqdhPOa%2BdVaLlvrWbjpmzgAPz6Q%2Fl8%3D&st=2018-09-14T07%3A50%3A53Z&se=2018-10-15T07%3A55%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-35) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140755033545-35%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cmbLirhgEAxsHc%2Fvsqa51PzHrlKen1gIQs1v08eGZW0%3D&st=2018-09-14T07%3A51%3A18Z&se=2018-10-15T07%3A56%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
