### PR TITLE
pr2

### PR DESCRIPTION
**Pull request by LucasDvp**

### CODE REVIEW

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr2/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140701560790-29%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2TvFfDNq0PyeXaHaur0BkDx8aPy35%2F%2BfdNk0KHQF7W4%3D&st=2018-09-14T06%3A57%3A42Z&se=2018-10-15T07%3A02%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr2/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140701569709-29%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=W%2B768dR%2FUFP3BVIFsekGnaO2kG6UmuKzAe%2BPv2cCek8%3D&st=2018-09-14T06%3A57%3A49Z&se=2018-10-15T07%3A02%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr2/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140705479822-29%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kx%2BW1bfdOy0FDD5d0NUAqoT2LeYwv0wxUg6qDmp09rQ%3D&st=2018-09-14T07%3A01%3A33Z&se=2018-10-15T07%3A06%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr2/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140705470691-29%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CIS4%2BVbwDbFHp4WLa1XKx%2Bps6ruXj3g9GUhu7wdSWxQ%3D&st=2018-09-14T07%3A01%3A38Z&se=2018-10-15T07%3A06%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr2/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140720451213-29%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oRKvM9NCIoB1xImxbTNn96lfPCEqmsqq22or6kNLqu4%3D&st=2018-09-14T07%3A34%3A35Z&se=2018-10-15T07%3A39%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
