### PR TITLE
pr2

### PR DESCRIPTION
**Pull request by LucasDvp**

### CODE REVIEW

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr2/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-37) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140814062142-37%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UYBvJWxJpoMXpiH2OdHTC6eTNjrPGBQw5Br7Hp9FnTo%3D&st=2018-09-14T08%3A09%3A52Z&se=2018-10-15T08%3A14%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr2/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-37) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140814058261-37%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jbJ6CCE1R04YgffJPkbboXMNiiFgDswNrn18L3Mj7iI%3D&st=2018-09-14T08%3A09%3A56Z&se=2018-10-15T08%3A14%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr2/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-37) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140829078607-37%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=D2C570ZAwcpW8fWzKd9lhkqz%2BDu5me6h%2FeqMTJu9ThU%3D&st=2018-09-14T08%3A24%3A54Z&se=2018-10-15T08%3A29%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr2/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-37) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140829171963-37%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wK4d9Wg4lSxFm7nvfxIxMRD7nVgAFhnDDqxMgG7fnak%3D&st=2018-09-14T08%3A25%3A08Z&se=2018-10-15T08%3A30%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr2/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-37) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140913226260-37%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kBy5d96brZSPXxvPttiufjg%2Bl9GKN90pd7WhLaupKbU%3D&st=2018-09-14T09%3A11%3A52Z&se=2018-10-15T09%3A16%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr2/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-37) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C17%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809170230184285-37%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=E8PVpePrlWYaerqAJV2NzoRa0soxoBrRyrU2EDkpxiw%3D&st=2018-09-17T02%3A26%3A06Z&se=2018-10-18T02%3A31%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
