### PR TITLE
pr5

### PR DESCRIPTION
**Pull request by LucasDvp**

### CODE REVIEW

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140729340431-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mW4UvzPixq3quXhCKVpDhANBUp38W9sw55PYvdIDZcc%3D&st=2018-09-14T07%3A25%3A20Z&se=2018-10-15T07%3A30%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140729342349-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XCTeabcogMQQgTyVv2fGCOzjJKSwhzk3JktQ9TKFdJY%3D&st=2018-09-14T07%3A25%3A35Z&se=2018-10-15T07%3A30%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140741596437-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zocC2BbS2JDuZGN%2BtIta4DgC%2BJCTLC8rMwqKibH3mvI%3D&st=2018-09-14T07%3A37%3A45Z&se=2018-10-15T07%3A42%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140741592347-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lKhAIfK8%2B8%2BGw7%2BDsGJgKae%2BR87p7oNJloJRiRhSzNM%3D&st=2018-09-14T07%3A37%3A50Z&se=2018-10-15T07%3A42%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140748097613-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kAsMCRQjsbVR8SD%2B2X4bolQHgvtcz1ZkUsRhTbwBfh0%3D&st=2018-09-14T07%3A43%3A55Z&se=2018-10-15T07%3A48%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140748101712-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XNL%2Fvrzad9BX8QaiifSK%2BPEndemvbx5fDNQaEOz5kUw%3D&st=2018-09-14T07%3A44%3A00Z&se=2018-10-15T07%3A49%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140754316955-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=raEJKk6NNq9FxaCw%2B6asqqqZSmGZsCkPHu8%2BEXroSe0%3D&st=2018-09-14T07%3A50%3A21Z&se=2018-10-15T07%3A55%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140754316801-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BeeIlBSsKhkxYVmhFPvABl4cyzfmoHNT6OfqaBayJPg%3D&st=2018-09-14T07%3A59%3A47Z&se=2018-10-15T08%3A04%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140808039661-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0H1bhVfTtqUxtO0It6qR1pQ6dlc4sVHZiEizxEYA7UY%3D&st=2018-09-14T08%3A03%3A49Z&se=2018-10-15T08%3A08%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140808135851-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=K6UUaHdqoPlTbOwEAcK4edqNWEbJG2IkMVwamc%2Bunss%3D&st=2018-09-14T08%3A04%3A03Z&se=2018-10-15T08%3A09%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140829496631-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mwzbGe0wPg1YYevsbFfch0BarLXx7wK6wrFN8l2jql4%3D&st=2018-09-14T08%3A25%3A56Z&se=2018-10-15T08%3A30%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140836578164-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7W8hYqOp1Gtj%2F4fMFv22dbH9W1iKhdVnYn27EIMTb6c%3D&st=2018-09-14T08%3A32%3A49Z&se=2018-10-15T08%3A37%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr5/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-34) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140836579325-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wydKR90NHVY1M16gqu1WJnb6%2FmxWr61JbI5q3IhV3sw%3D&st=2018-09-14T08%3A33%3A25Z&se=2018-10-15T08%3A38%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
