### PR TITLE
Master pr3

### PR DESCRIPTION
**Pull request by LucasDvp**

### CODE REVIEW

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-22) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C13%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809130837264824-22%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2dbawvZpLiagySPDGXuW5KpXrqmpBm9bSecCxfWx53Q%3D&st=2018-09-13T08%3A33%3A13Z&se=2018-10-14T08%3A38%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-22) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C13%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809130837286471-22%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BkBVWx6jnTRQjoHumhN4VXoVuz%2FOr%2FRZ9d60u%2Ffr7b4%3D&st=2018-09-13T08%3A34%3A42Z&se=2018-10-14T08%3A39%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-22) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140202543882-22%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=r0BeQ%2BZ%2BitvgdTAqNUEuqyE8BHcjjrzEt6w2Alce%2Fqs%3D&st=2018-09-14T01%3A58%3A41Z&se=2018-10-15T02%3A03%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-22) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140202542824-22%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VL8Si2iSqXVQ5Gg88kx%2BsC0ypioJZgi2i9A0zIlE5A0%3D&st=2018-09-14T01%3A59%3A09Z&se=2018-10-15T02%3A04%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
