### PR TITLE
Master pr3

### PR DESCRIPTION
**Pull request by LucasDvp**

### CODE REVIEW

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140729124899-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xiRxp59JTIaQuNexmWl%2FxNU%2FuxLCNhAqGDQakZlycXI%3D&st=2018-09-14T07%3A25%3A02Z&se=2018-10-15T07%3A30%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140729411041-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DvfYvWoHuexQ4ZdPRnx138fJXTPOQjmYo16nFjhvgLk%3D&st=2018-09-14T07%3A25%3A43Z&se=2018-10-15T07%3A30%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140742185702-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=W9%2FQ2%2B8NHM39U17rs4IiUQTHgLV3THycCcyi%2FcAmrHY%3D&st=2018-09-14T07%3A38%3A07Z&se=2018-10-15T07%3A43%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140743123708-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=O7aY%2FQ4U8qB0X9mDo8gXx661y5oygbptXudDXvhGjCs%3D&st=2018-09-14T07%3A39%3A08Z&se=2018-10-15T07%3A44%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140748215918-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Zl8LKbJS2mGy8PJOxHZ6MDvnUR8M0DBVs7IgZ35h3dg%3D&st=2018-09-14T07%3A44%3A12Z&se=2018-10-15T07%3A49%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140748210564-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1fwyE7hFdxPx6oJGvq1H9OVQNeWz57yQg9t1Bqp%2BBZQ%3D&st=2018-09-14T07%3A44%3A20Z&se=2018-10-15T07%3A49%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140754284657-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GdznFBhy0x3eD1X61gXWdWAHNtgIjQKzQh0X5CFbw%2Bg%3D&st=2018-09-14T07%3A50%3A14Z&se=2018-10-15T07%3A55%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140754381200-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6%2BVAUq6leRCe3sSsGXwbAX6i2R%2BgQRoIPI8DDbvCa4s%3D&st=2018-09-14T07%3A50%3A25Z&se=2018-10-15T07%3A55%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140829445905-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IBcjGWSry94dBdU4uEKZpC5h9vJFpqMsoeHoixaEi64%3D&st=2018-09-14T08%3A26%3A38Z&se=2018-10-15T08%3A31%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140837332076-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=C5VuJGoOzGve24VOh39e%2FJAtm%2F%2FtlJcgSOUVeMAbT%2BI%3D&st=2018-09-14T08%3A33%3A22Z&se=2018-10-15T08%3A38%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140837331089-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kzumrBu2myrfbtK9Bqe69%2F9kd4MSpbkB%2FENIVV3kiqM%3D&st=2018-09-14T08%3A33%3A51Z&se=2018-10-15T08%3A38%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr3/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-33) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140840589961-33%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eIRzLxbKjhKicV6mU3DszMEj4HNQ11VqZUjOtI6ghYk%3D&st=2018-09-14T08%3A36%3A50Z&se=2018-10-15T08%3A41%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
