### PR TITLE
pr4

### PR DESCRIPTION
**Pull request by LucasDvp**

### CODE REVIEW

**Comment by LucasDvp** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-)
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

<a name=""></a>
### []()
 - **[Warning]** Skipping file W:\4nmu-s\.optemp\packages\docfx.console.2.40.0-b-180905008-g569b638\tools\plugins_n4yth2p4.a1m\plugins\DocumentDB.Spatial.Sql.dll due to load failure: Could not load file or assembly &#39;DocumentDB.Spatial.Sql&#39; or one of its dependencies. The module was expected to contain an assembly manifest.
 - **[Warning]** Skipping file W:\4nmu-s\.optemp\packages\docfx.console.2.40.0-b-180905008-g569b638\tools\plugins_n4yth2p4.a1m\plugins\Microsoft.Azure.Documents.ServiceInterop.dll due to load failure: Could not load file or assembly &#39;Microsoft.Azure.Documents.ServiceInterop&#39; or one of its dependencies. The module was expected to contain an assembly manifest.

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C6%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809060356346579-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TCy5B5bD5HjCaBNJjp55qLRb6Eo4MoQvkJL5hqPBJYo%3D&st=2018-09-06T03%3A52%3A35Z&se=2018-10-07T03%3A57%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-)
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

<a name=""></a>
### []()
 - **[Warning]** Skipping file E:\wwbe-s\.optemp\packages\docfx.console.2.40.0-b-180905008-g569b638\tools\plugins_l42mywod.3lp\plugins\DocumentDB.Spatial.Sql.dll due to load failure: Could not load file or assembly &#39;DocumentDB.Spatial.Sql&#39; or one of its dependencies. The module was expected to contain an assembly manifest.
 - **[Warning]** Skipping file E:\wwbe-s\.optemp\packages\docfx.console.2.40.0-b-180905008-g569b638\tools\plugins_l42mywod.3lp\plugins\Microsoft.Azure.Documents.ServiceInterop.dll due to load failure: Could not load file or assembly &#39;Microsoft.Azure.Documents.ServiceInterop&#39; or one of its dependencies. The module was expected to contain an assembly manifest.

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C6%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809060357069267-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gyAGDBtHMYv%2FOwLQfX88KkrnW5NeY%2FDvHKdki8tw9u4%3D&st=2018-09-06T03%3A58%3A26Z&se=2018-10-07T04%3A03%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140247141560-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Ox0llNhrNxcCwJS%2FuG%2BXYWQ88E7Zzd7b5PUpv6Css9U%3D&st=2018-09-14T02%3A43%3A13Z&se=2018-10-15T02%3A48%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140249256743-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MPAOE4KHKQ7ZEgiR9UztVKGdzD0i0M3MHjW1NpqYVcQ%3D&st=2018-09-14T02%3A45%3A17Z&se=2018-10-15T02%3A50%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140249441058-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TTHYBNplYO9a2fMxcWdBmNp8uxhLs6bhve10N8c12x8%3D&st=2018-09-14T02%3A52%3A03Z&se=2018-10-15T02%3A57%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140516175830-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0ePtS7sqU8IspGXxXXjoa6F4qpf%2B5JFhwou2fMgAw7U%3D&st=2018-09-14T05%3A12%3A14Z&se=2018-10-15T05%3A17%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140545582790-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rTTd3eyEyJIZODItz4HPMBvmy0j4jKrLiigYqkNrssg%3D&st=2018-09-14T05%3A41%3A46Z&se=2018-10-15T05%3A46%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140545579429-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0s8tQQtXN4il%2BidQ7gG%2FxQ6lt%2Bmm%2FJ8MIK82zZqCJIg%3D&st=2018-09-14T05%3A41%3A47Z&se=2018-10-15T05%3A46%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140552518050-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Q8TmGyM%2FBDReW9LbTyTo3A7x3X%2FmTyZg8ijYDPvCY5w%3D&st=2018-09-14T05%3A48%3A37Z&se=2018-10-15T05%3A53%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140552515461-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jhdJM3xE7B7YdxDJ7%2FGEuICZsEp677iwRP0TA1X3RXs%3D&st=2018-09-14T05%3A48%3A39Z&se=2018-10-15T05%3A53%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140553454188-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=T6fGT7pn%2BJWrGG9EiJuo1SkasecTDKTe2rrogMMGmsM%3D&st=2018-09-14T05%3A49%3A31Z&se=2018-10-15T05%3A54%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140553452815-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gv3jWd%2B13EzaqEPTXDT4BCIkpK%2Bq4vDYsL5T5TfflbQ%3D&st=2018-09-14T05%3A49%3A35Z&se=2018-10-15T05%3A54%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140558226362-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CvQBexeGGKSx9g%2FEjNd6dR8w%2Bjfc1Pd%2BM%2BaW7pbXa%2BY%3D&st=2018-09-14T05%3A54%3A15Z&se=2018-10-15T05%3A59%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140603182724-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2vaMiCMOBT8A8OOo8LjagG840XtnunspFOqQo6TUnjs%3D&st=2018-09-14T05%3A59%3A11Z&se=2018-10-15T06%3A04%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140603189956-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MO9npBCfkaHIfIt3%2BCkhHjByj%2Fs4eZURXuDSYdszI5w%3D&st=2018-09-14T05%3A59%3A41Z&se=2018-10-15T06%3A04%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140605358395-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Xi5zgXgbwBD9BMIDkE5xthewqqbOD4XCuK2aNK5ejR8%3D&st=2018-09-14T06%3A01%3A27Z&se=2018-10-15T06%3A06%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140605466621-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sIFJXtUWsai0tB4Cewgup5fK5OjSPDLQORUy%2B5v5PC8%3D&st=2018-09-14T06%3A01%3A31Z&se=2018-10-15T06%3A06%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140613116795-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=21C6VVGeoRB%2FBkLs7rHfJV3S81iqZkQ035yOyqxeJpg%3D&st=2018-09-14T06%3A09%3A13Z&se=2018-10-15T06%3A14%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140613114359-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=R%2FFnmcoWeNUrkN5A06SqwOF54YjTZjCsOEbcXYqI05E%3D&st=2018-09-14T06%3A09%3A34Z&se=2018-10-15T06%3A14%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.msdn.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageperf.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140742519853-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FMHser5UdEU4MTbliBlQR4ccafmBbaJNdvaXK74Jugo%3D&st=2018-09-14T07%3A38%3A56Z&se=2018-10-15T07%3A43%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by partychen** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[fenxu_docs_20170411/index.md](https://github.com/fenxuorg/fenxu_docs_20170411/blob/master-pr4/fenxu_docs_20170411/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/fenxu_docs_20170411/index?branch=pr-en-us-5) |

For more details, please refer to the [build report](https://opbuildstorageinternal.blob.core.windows.net/report/2018%5C9%5C14%5Cf2c0ae42-5a30-61b7-7181-96e5b4b30845%5CPullRequest%5C201809140742520678-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vVNflbKCeuOChZQqs7Vds7O1eAk5tbigpIFKudVCYD8%3D&st=2018-09-14T07%3A48%3A17Z&se=2018-10-15T07%3A53%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
